### PR TITLE
Updated gradle to latest version and updated Strings.xml

### PR DESCRIPTION
**Pull request by TheMaxCoder**
Hi rettyy, I would like to help you in building this project and thought of updating the Strings.xml with proper English.
If there is anything else you want me to do I will be happy to help.

### CODE REVIEW

**Comment by erttyy8821** [comment]
Thank you!

**Comment by DaxiaK** [comment]
Thank you!
I will merge it and update to Google play!

**Comment by TheMaxCoder** [comment]
Your welcome and please wait, do not update it on google play yet, I have few improvements in my mind that i will make today or tomorrow then you can update the google play version.

**Comment by DaxiaK** [comment]
I had planned update supports English version at yesterday! And I will add width and position seekbar in next version , maybe I will finish it and release in this weekend.
You can do slowly , it's okay! This project just was used for my device to solve hardware button problem :)

**Comment by TheMaxCoder** [comment]
Okay great, I updated the GUI of MainActivity and Permission Dialog but I was having some merge conflicts because you made some changes, I will resolve them whenever I get time :)

**Pull request merged**
